#!/bin/sh

docker run -dit \
           --privileged \
           --name c75-demo-1 \
           -h hw-c75-1 \
           -p 10001:22 \
           -p 20002:80 \
           c75:v1 \
           /usr/sbin/init
